XXX XXXXXXXXXXXXX  
    XX XXXXXXXXXXXXXX XX XXXXXXX  
        XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX  
        XX XXXXXXXXXXXXXXXX  
            XXXX  
                XXXXXXXXXXX  
                XXXXXX XXXXXXXXXXXXXXXXX  
            XXXXXXX  
                XXXX  
    XXXXX  
        XXXX X XXXXXXXXXXXXXX  
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  



XXX XXXXXXXXXXXXXX  
    XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX  
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  




XXX XXXXXXXXXXXXX XXXX  
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX  




XXX XXXXXXXXXXXXXXX XXXX  
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXXXXXX  
    XX XXXXXXXXXXXXXXXX  
        XXXXXXXXXXX  
        XXXXXX XXXXXXXXXXXXXXXXX  
    XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX  



XXX XXXXXXXXXXXXXXXX XXXX  
    XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXX  
    XXXXXXXXXXXXXXXXX  
    XXXXXX XXXXXXXXXXXXXXXXX  