# Generated by Django 3.0.7 on 2020-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'France'), ('AR', 'Arabic')], default='ar', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
