# Generated by Django 3.0.7 on 2020-07-02 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0013_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medias',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
