# Generated by Django 3.0.7 on 2020-07-03 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0015_comment_reply_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_heart',
            field=models.ManyToManyField(related_name='likes_heart', to=settings.AUTH_USER_MODEL),
        ),
    ]
