# Generated by Django 3.0.7 on 2020-07-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_article_likes_heart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes_heart',
        ),
    ]
