# Generated by Django 3.0.7 on 2020-07-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20200705_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_comment',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
